name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'alpha'
      - 'beta'
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  issues: write
  pull-requests: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: .NET Build
      run: dotnet build -c Release

    - name: .NET Pack
      run: dotnet pack -c Release -p:Version=0.0.1-alpha${{ github.run_id }}

    - uses: actions/upload-artifact@v4
      with:
        name: NuGet
        path: src/**/*.nupkg

    - name: .NET Test
      working-directory: tests/CSharpUI.Avalonia.Tests
      run: dotnet run -c Release /p:DebugSymbols=true /p:DebugType=full -- --trx test-results.trx --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml

    - name: Test Report
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: Tests
        path: tests/**/test-results.trx
        reporter: dotnet-trx

    - name: Coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.cobertura.xml
        fail_ci_if_error: false

  create-release:
    if: ${{ github.event_name != 'pull_request' }}
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v5
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        extra_plugins: |
          conventional-changelog-conventionalcommits

    - name: .NET Pack
      if: steps.semantic.outputs.new_release_published == 'true'
      run: dotnet pack -c Release -p:Version=${{ steps.semantic.outputs.new_release_version }}

    - name: NuGet login (OIDC → temp API key)
      if: steps.semantic.outputs.new_release_published == 'true'
      uses: NuGet/login@v1
      id: login
      with:
        user: IvanJosipovic

    - name: .NET NuGet Push
      if: steps.semantic.outputs.new_release_published == 'true'
      run: dotnet nuget push src/**/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ steps.login.outputs.NUGET_API_KEY }}
